title: Sree Vidya Mudduluru
logo: /assets/img/logo.png
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/sree-vidya-m-4364162a/">LinkedIn</a> |
  <a href="https://github.com/sreevidyamcsr">GitHub</a>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
